{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.khazardstudent.media3",
    "module": "media3-extractor",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.9.0.aar",
          "url": "media3-extractor-1.9.0.aar",
          "size": 819952,
          "sha512": "e1a1b88039877649fee7e43e1e74e1e7f73112c82015db8772a16ea68f0375926171da05b12d03fda6fe82f22b2281ba717d99f4a4b62b632f63f83a6048f419",
          "sha256": "35c7d6fb204da442f251c0079477e32ba17e42c7819886105176055ef98b99e3",
          "sha1": "835e5c426fd2e45c30965fee9ed6be518a30fcf7",
          "md5": "471389e24df2aaddf33c6869813a5d68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.9.0.aar",
          "url": "media3-extractor-1.9.0.aar",
          "size": 819952,
          "sha512": "e1a1b88039877649fee7e43e1e74e1e7f73112c82015db8772a16ea68f0375926171da05b12d03fda6fe82f22b2281ba717d99f4a4b62b632f63f83a6048f419",
          "sha256": "35c7d6fb204da442f251c0079477e32ba17e42c7819886105176055ef98b99e3",
          "sha1": "835e5c426fd2e45c30965fee9ed6be518a30fcf7",
          "md5": "471389e24df2aaddf33c6869813a5d68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-extractor-1.9.0-sources.jar",
          "url": "media3-extractor-1.9.0-sources.jar",
          "size": 709599,
          "sha512": "24b3df0312086f26688b4f54263eac16bab4d922aeef0d07a9e32f7183b8858ec6236c0f5b291b5b8a8f96733a0a9e7ff50c98a4947bb3cac5dc043a74105b87",
          "sha256": "48cfba63d43c5bb0c655b18ac7f2558a4f31c03c244ac82600bdd4729f3d2ce2",
          "sha1": "67b966325e0b24543d0f93ab17b5012a6c2332b7",
          "md5": "ef1a34f980e0ef30488cc0cae7ba34a1"
        }
      ]
    }
  ]
}
