{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.khazardstudent.media3",
    "module": "media3-decoder-ffmpeg-ass",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-decoder-ffmpeg",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-ffmpeg-ass-1.9.0.aar",
          "url": "media3-decoder-ffmpeg-ass-1.9.0.aar",
          "size": 913,
          "sha512": "3335cdf9319de263c66323f650cb4cf1e5f6b421168c3af2f885b37df7e66614f8559fa43d15aedd07f8f9df1bd50127ae857dedc6b6fcad64e8aa2a64419b51",
          "sha256": "18938915f9cbb4ba1ec5d145462af0574ffbb0df63587f709c7663de8aa8a4be",
          "sha1": "ea0b384fc351ac7c6be9b8b35936202fd032aa9b",
          "md5": "ad6a2aa2009e7f4707fdf400b9d6d9da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-decoder-ffmpeg",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-ffmpeg-ass-1.9.0.aar",
          "url": "media3-decoder-ffmpeg-ass-1.9.0.aar",
          "size": 913,
          "sha512": "3335cdf9319de263c66323f650cb4cf1e5f6b421168c3af2f885b37df7e66614f8559fa43d15aedd07f8f9df1bd50127ae857dedc6b6fcad64e8aa2a64419b51",
          "sha256": "18938915f9cbb4ba1ec5d145462af0574ffbb0df63587f709c7663de8aa8a4be",
          "sha1": "ea0b384fc351ac7c6be9b8b35936202fd032aa9b",
          "md5": "ad6a2aa2009e7f4707fdf400b9d6d9da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-ffmpeg-ass-1.9.0-sources.jar",
          "url": "media3-decoder-ffmpeg-ass-1.9.0-sources.jar",
          "size": 727,
          "sha512": "f5bfb823851717efa996e7079b49ac912f75005e28c3bc8d5ddf3cab0bae7209e3fd9b7092e094b55f26bca891e0b3fced248b95982292c5053c17c441e83ddb",
          "sha256": "52b471289bfffc577d157a859b48c67234165c95eb54160e21255f1873f42889",
          "sha1": "7bd8633e0caa201e29efc456e653f85a3bae8a3d",
          "md5": "a08b7c66b2a8e936a5993495c924cc6e"
        }
      ]
    }
  ]
}
