{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.khazardstudent.media3",
    "module": "media3-common",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.9.0.aar",
          "url": "media3-common-1.9.0.aar",
          "size": 588495,
          "sha512": "4ec3daf398ad03bdbb0cb7844d425b1aa5b08e239590fbd5742788e058e1bbe32e45c90178d11119d06cad93c97e3565f0965b1df385de153c04916c36f1cfdb",
          "sha256": "0658956c5ba234185b84a9cd92e1771c6d51d9c7489345b85007992141d78145",
          "sha1": "8d32eb649f30221ba520bc8c6a09ad548e6207a6",
          "md5": "6cf73cc88a56202364160a0ccacdc0fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-cast",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-datasource-cronet",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-datasource-rtmp",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-exoplayer-midi",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-exoplayer-workmanager",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-inspector",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-ui-compose",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-ui-compose-material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-ui-leanback",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-test-utils",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-test-utils-robolectric",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.9.0.aar",
          "url": "media3-common-1.9.0.aar",
          "size": 588495,
          "sha512": "4ec3daf398ad03bdbb0cb7844d425b1aa5b08e239590fbd5742788e058e1bbe32e45c90178d11119d06cad93c97e3565f0965b1df385de153c04916c36f1cfdb",
          "sha256": "0658956c5ba234185b84a9cd92e1771c6d51d9c7489345b85007992141d78145",
          "sha1": "8d32eb649f30221ba520bc8c6a09ad548e6207a6",
          "md5": "6cf73cc88a56202364160a0ccacdc0fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-common-1.9.0-sources.jar",
          "url": "media3-common-1.9.0-sources.jar",
          "size": 479703,
          "sha512": "88117277d46e0acbc705a5d41ea04da7146eb438194d4dff08300a3425361ddb5358ed80c68e72d14f1b920db003ca37205039bdc525134651bee565c63900d9",
          "sha256": "1cac0f446991c8c371d0c7df821245b546a0a2f62dc930b579086480054ba54c",
          "sha1": "32e63a66d624779a1bdf92e2b03acd2b64e62ced",
          "md5": "1a58db0ccedc901effdc60022a1b2ffc"
        }
      ]
    }
  ]
}
