{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.khazardstudent.media3",
    "module": "media3-decoder-ffmpeg",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-ffmpeg-1.9.0.aar",
          "url": "media3-decoder-ffmpeg-1.9.0.aar",
          "size": 22831967,
          "sha512": "919b5ec5c64c428c83b25cb35d97b27424c1c96ddd05620f1d4b4ce5ef161ce1a2b2ba4d3ac273219158e9de5bd0f7ad6731be1f88e5ce58d4814a56d42eeba9",
          "sha256": "208e6d0c3cc96d7944d7c5552c25aedd665654dba3aad1faacd84ce567bd3458",
          "sha1": "81d2f7a3d5d6f0a876553c276dd63b73b39a3938",
          "md5": "4b195293e202f26b08a0bd2071ee113e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.github.khazardstudent.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-ffmpeg-1.9.0.aar",
          "url": "media3-decoder-ffmpeg-1.9.0.aar",
          "size": 22831967,
          "sha512": "919b5ec5c64c428c83b25cb35d97b27424c1c96ddd05620f1d4b4ce5ef161ce1a2b2ba4d3ac273219158e9de5bd0f7ad6731be1f88e5ce58d4814a56d42eeba9",
          "sha256": "208e6d0c3cc96d7944d7c5552c25aedd665654dba3aad1faacd84ce567bd3458",
          "sha1": "81d2f7a3d5d6f0a876553c276dd63b73b39a3938",
          "md5": "4b195293e202f26b08a0bd2071ee113e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-ffmpeg-1.9.0-sources.jar",
          "url": "media3-decoder-ffmpeg-1.9.0-sources.jar",
          "size": 12360,
          "sha512": "cc8973878de59b3396cbfeeeb5ccfc87519e589f28ee7e4e6e6390ebe51299e1bc8d0a92d9a23a796b1704a012c4c85ccaee5fcd5b6007ccada327e6d8612c2b",
          "sha256": "139bc6ced45fc10a64a890cfd532b51d86752ef4c17ab80a7d2d925a5990e209",
          "sha1": "79f0b6863f9246a022767ba0ee0f9c534a940c56",
          "md5": "835cc6542cf747074bcc59191c38a919"
        }
      ]
    }
  ]
}
